apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sncf
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/feven-redhat/fullstack-app-sncf.git
status: {}
