kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: headquarter-shipment-records
  labels:
    strimzi.io/cluster: headquarter
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
