apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: headquarter
  name: headquarter
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: headquarter
    type: scram-sha-512
---
apiVersion: v1
stringData:
  password: h3adqu@rt3r
kind: Secret
metadata:
  name: headquarter
type: Opaque