INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Mango');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Strawberry');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Orange');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Lemon');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Blueberry');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Banana');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Watermelon');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Apple');
INSERT INTO Fruit(id,name) VALUES (nextval('hibernate_sequence'),'Pear');